### ISSUE TITLE
Feature Request - Ability to select child folders and import

### ISSUE THREAD

**Issue by TornMarketing** [dd32/add-from-server#3]
We have a heap of posts we have migrated with embedded content, content that doesnt import through the normal means.

We have copied the uploads hierarchy for which we have alot of images spread 5 years.

We would be keen to find a means to import all assets within the child folders of the upload directory without having to jump into each page, wait for all the assets to load, select etc.
ie 
2021/04/
2021/03/
2021/02/
2021/01/
2020/12/

**Comment by dd32** [comment]
Bulk imports are not a planned feature of the plugin.
