### ISSUE TITLE
Wordfence says that the plugin is abandoned

### ISSUE THREAD

**Issue by soleto** [dd32/add-from-server#7]
Hi there!

I have not really an issue, but I didn´t know how to contact. It is just that Wordfence plugin reports me the more than 2 years of inactivity of this plugin.

Also Wordpress says "This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress."

Is dangerous still using this plugin?

Why you says that "An outdated 11 year old plugin that over 100k people still insist on using"? Hahaha!

Thank you in advance!

**Comment by dd32** [comment]
Plugin still works, plugin hasn't been touched in years, it's expected that it'll have the "Untested with 3 versions" warning.

Complain to WordFence about them nagging about old plugins. An old plugin doesn't mean it's a bad plugin or unsafe to use.
